import NavBar from "@/components/navigation/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PolybaseProviders from "@/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-[1093px] flex mx-auto flex-col">
          <PolybaseProviders>
            <NavBar />
            {children}
          </PolybaseProviders>
        </main>
      </body>
    </html>
  );
}
